# Generated by Django 6.0.2 on 2026-02-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbottle',
            old_name='sku',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='current_qty',
            new_name='current_quantity',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='supplier_by',
            new_name='supplied_by',
        ),
    ]
